apiVersion: v1
kind: Service
metadata:
  name: ranch-management-tailscale
  namespace: ranch-management
  annotations:
    tailscale.com/hostname: ranch-management-tcp
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    cnpg.io/cluster: ranch-management
    role: primary
  ports:
  - name: ranch-management-tcp
    port: 443
    targetPort: 5432
    protocol: TCP