apiVersion: v1
kind: Secret
metadata:
    name: ranch-management-db-password
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:AMf6Sg15+WQY73Vn5FeG6g==,iv:u6/m0+bfkFVcjm0ldFwC+OyrAZ6PAEJqB4EfMV8pkx4=,tag:5YZBObK4IkxHDZbyhNfG+Q==,type:str]
    password: ENC[AES256_GCM,data:nSDKZrlyM/Q=,iv:6rO6fupVSm5cpgdvwiNKHtik8bygk9/ifeBuBbLAe5s=,tag:f7xviQgmunZNoI3ZvHUQag==,type:str]
sops:
    lastmodified: "2026-04-29T00:09:21Z"
    mac: ENC[AES256_GCM,data:QoqXf5N4lKgMoLZ3l1up3hH6E94ViJPNA8PEtJRrcVg56pU1faEGfn9wC9HINnca0JwWEaUqWUa1A5KMa14PAEgqc0D3gpSruNnZe1BCNljUtzX++YeJJ/IjQKJEPRvjzgYr4voYanG0mUJy4j3e45CWom5ekFfIU7rV5x5Uzjw=,iv:wDWOMDXBMNy+Gqlx5T8FSg4QdnudADm4kL4IoBpl9YA=,tag:XddzRsXPYM1xWLIpcapZfA==,type:str]
    pgp:
        - created_at: "2026-04-29T00:09:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5XGugaz6vRlARAAhZERRF5MLrtgYR5bQpOJFgs7IP879bDPvmXmlR0lwK93
            bJQLVpPqDwQ1gTWY6kxDcalKR/x/3NPB+mbt1HeFDJml1T+IOtUdRIBsUs06/lPR
            v1Ih6pO3n07NZWk78rGi/RJVNct04nhAxRCTDYatyRQsac+VeNj0jfdZmx9Uq7X1
            03jIxrI0B4jlvcInq2bLYlSRD9sG+3Gbu5dR6XTSMKokKeUOelew8xNpxneZ4HqJ
            wZJAVkzOL7yWWOVZWyNWiVSfPl4zlmkrNxPiwLkGA0zLGvtAgR6AlTt/TPGlRsbm
            z2xTg19jgoNkn8ldLxnaxTif/8V1PYizw8Gi2bAMVi8AgqVvvtNnyEZhlgoa3rHk
            QDyUukSLoCJ5cC60ydnTZRHYzlvOfPM3g/Ax7zwDcFKcHfMojXT+d0U6zSODlazs
            MthwuRUSvLAVESV29lBClvImFuqt1JMODTgdNMrVEsn8F0ECY/vHk+7NBGl3kNCx
            kPnSBd4bM87cSRnPqc2L+PHDnuVXr9cNmEGBymzoiAlOwopanTcrPZtVaXohkWF3
            evOACEft7Pm+rUCLH/R20DCw7TA7fmsDw3tkU+vegU4u6NKQgunlO/s+HqBfe69C
            25RfymBjAdIfEfBBOtcHoKOBYx+c3lPBWqG/+6jaPyqHI2kV4IulN8YZRxI8FILU
            ZgEJAhAH8WxhxkY05lrgeUQP3yg83YrR0B5Y39JxKiQt9E57dM++r7M/wUl8AwVk
            n2qIz40Si760AsaZPkPOGaGMu378wqiDIKze4rpiVobCh46JN5qhmNijF5JqUJ87
            ZHL91aAf/A==
            =k2fm
            -----END PGP MESSAGE-----
          fp: FB5C16FB8DB546BB01DE0ED9DCCC989D57A72B56
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
