apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tailscale-operator-gateway-api
rules:
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses
  - gatewayclasses/status
  - gateways
  - gateways/status
  - httproutes
  - httproutes/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tailscale-operator-gateway-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tailscale-operator-gateway-api
subjects:
- kind: ServiceAccount
  name: operator
  namespace: tailscale
