apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: tailscale
spec:
  statefulSet:
    labels:
      app: tailscale-ingress
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9001"
