apiVersion: v1
kind: Secret
metadata:
    name: supabase-secret
    namespace: supabase
type: Opaque
stringData:
    jwt_secret: ENC[AES256_GCM,data:7wc9VrvFbYskDiOmw0GDcXoXlvaH5r1swxW4UZXxUwOFJtmIujbH1A==,iv:0TiADVxnqoaF6T5Fq84o4zydgDoCZ6CVzH/yrXi39Zc=,tag:Hz7LuuZiJ+6l8S9YKZbjfQ==,type:str]
    jwt_anon_key: ENC[AES256_GCM,data:WUcBXxbX4Rk+oXmUj916OeiCJ9hDcUxaKIPB4PTEdZArY1/w2/B5Ts061UCwH4ZkcpZY+n/V3PEqYMOjyV73NXIJCobmMbiR/8yxb5IsKI3ccrPRGp2H9ui/4R/KGTKLKPFObCN/yq9AkdBqZYDSfD0JoXFsfVxwQTOjB94K9THV8nkbLu2Uf+CjK7UfOCVMzUl/rYpcLb9XrVvPLyyk1RDB0eY3wxhsWQ==,iv:YXcJiTVrdx0Gz86DxFeREaqizrL6D2l/YqmCJ94rE70=,tag:VKwP9pwjHt9td31oKzUOcQ==,type:str]
    jwt_service_key: ENC[AES256_GCM,data:iTFnEPqlCM9SznfTIUTPzkfhzBs6B0XGtLKX2ReCE9RSLCcypyCgh/nwpqHEMUVcXjQuaeqFa6LEwK5emDEcCjWbaq1bOA87HH6U+KuHUdTgv4j/oZQPMk2NNZajmwykrRQCw7ScDN1mbV5Jsh/lTIFUePOCsVJI4Y/PV+2m+w+s6QoUv9oZHMiVT0b9p0LVeyb7alcKMV5hr7mqHe3IRkxEhsGzg3CEz3l6Ahc3miSQ05ik,iv:3/CVA+rsEES1fwJN1HhhEy42FZrA1daivxkktzXldmU=,tag:M1BlNkIPjyWNTiim8+zTgg==,type:str]
    db_password: ENC[AES256_GCM,data:M7Ki7+PQ8O4=,iv:9QApPZqfcm+pEyaIZSZASz2OwMoNN6DHq20kLSDY49U=,tag:yr94NiBqX0PDne/dpGpKsw==,type:str]
    dashboard_username: ENC[AES256_GCM,data:9W063McRLcs=,iv:fJqYs/RhXY0hngzmMUuXgz5EZ1y4gZ9dpkTKFODBFQM=,tag:+pwOLWwGAQ2NoBS2xPnIFQ==,type:str]
    dashboard_password: ENC[AES256_GCM,data:7+u9dCmyyAQ=,iv:qBp1iyoe5xLAW73n+KVEaOY2Z37JXQ7Zz9aIDxeYUMY=,tag:PM166epfaOEBTzcaZ/nEJQ==,type:str]
    analytics_api_key: ""
    smtp_username: ENC[AES256_GCM,data:FUJejTPE0zA=,iv:7eDfZpAGLk7/bxUj6ik8fHikjXweuW7Wd0vEn4DAJ5A=,tag:F2+5g91NXtbphWvMdwkiHg==,type:str]
    smtp_password: ENC[AES256_GCM,data:IwOmrOMyDY0=,iv:JIdY5dufToP+FBZGnB+teecJVW9Qwna8ngqwpdeJvw0=,tag:wdepc/myfUG23/nG9S2g2w==,type:str]
sops:
    lastmodified: "2026-03-16T17:30:30Z"
    mac: ENC[AES256_GCM,data:uzJxUJaMXEvddpBAU1Ed0rgKHJjjCPABtDNKVEiGU5G4H194GfdaPWxmgE9zcSImcw/A0hUOpTRBuggK2TCAMl5qk2Cuy3ePgRAxSOcmJoDVwC8c46E6sIWxXGJzdV/UDIst/YFfIvQGaIRPNOnnYr9mznlbSEM1b13QI+c/Uz0=,iv:txMYySCdyhZ2fcn/QbGSDCY2Ey/rzHqP8PJMoayHcA8=,tag:l5wLay+0p0pE7VWqbkTaJA==,type:str]
    pgp:
        - created_at: "2026-03-16T17:28:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5XGugaz6vRlAQ/9E+HELjzU+/TaAJ2hETHVQbl70io/X6JyR1fisnpS1/ZE
            jPT+29q9fpX33yY+2EWWQlwhd2rISTcc54vMPVN6iSCJfeVzHYnusblzVJ9tJO6/
            wkmahHeFiBzSmQdx3ZSgAvVjovEi+6JREZvgczHlbsPigz2UUEF53GLc7RwL1WiD
            an7y7MzFfp+ZWhNjOhQY9ZC/F/MURPFrZwzMTznLBx9V4rI5rhfFbJihTkSh1Nsy
            LEOvHSNnNqYgEDTZUjLf9YAHiJaa78dZLlavW+QQHXnCyh9K29J0hDbRYtJNh5jP
            2i2xQLNtSmxuzD3RQVxbqSnjyT7tafHR9PB/2YfQ9rBIvAL88LacySc4e9uSbVt8
            r0lCYZ5mP/yiLPcax4uDXIHpzCQg9T3uN3qRKDUMpqTiBMWDj1JVYd+TtvmXHpjc
            PgFv4u9OCfpTonAATSVM26riw8gd3OHjYiAXRzHZKB79nYI8LFpk7nbtQJBOETSl
            1zxJbmP4kU2wce1/2Gfhz9CgKNl/o0SoA40CEsY/RVlRccmiGHpceW30yAeFut+z
            dxEm8r2wjqYmjO8OpzYNZ++k0tTa7iRfwUiZ0IncLSmJzqswi2R+SLs7TJgsonWt
            s7HQYYqZMh9Jb52ytMyhEXz/Hik15Pnn6/kOZj51Aq5xD3kjswWSIxqesKYkfTDU
            aAEJAhCli3NkChKcnBhmwLxv9tgQ5L6YVZ9EjzPlXMgV85JYQC51/AyqeoiTJ10b
            bxaxXi7pVzqfxslLYeA4YjlM6wJV42MLf3lgXEiyJOZhMOn9+xQPSDNShoWMLsqJ
            IVMZfg3ktX1o
            =60Yk
            -----END PGP MESSAGE-----
          fp: FB5C16FB8DB546BB01DE0ED9DCCC989D57A72B56
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
