apiVersion: v1
kind: Secret
metadata:
    name: supabase-secret
    namespace: supabase
type: Opaque
stringData:
    jwt_secret: ENC[AES256_GCM,data:HBz18gkzy8QHeUutSuhKx5LOKtKcZefifd1RWdFuGltPXnOrGfJiptR0yqg=,iv:uzT+pGcOCFor3lcys5t1JEG3sx+7Oxi8oQlo2JEiQ70=,tag:VPaxjVR1pb/1QQj3GpQ5Ew==,type:str]
    jwt_anon_key: ENC[AES256_GCM,data:5R7MMa/7npT0tizjbobpR/PW4e9m50OhCpwbAKMWTIqqE71FUlP59IfkBaM=,iv:3+sY89+4VafybYFgBKHkx2VYj+E6clsc8CyFOW4kvAE=,tag:z+sYtpjy9OtgRcNlm/DpeA==,type:str]
    jwt_service_key: ENC[AES256_GCM,data:KKA7N5AZ+1YdV7c/jJ2QFCd/ymOHtSnHfR6OtozTB335VBEeV3iUkqEAoO8=,iv:iJdSxkR5bLVSoQ1BuR06w6DOcguM9O0aaqqJ9127taM=,tag:yw0ufLT1n8BacnkCDnR8jw==,type:str]
    db_password: ENC[AES256_GCM,data:Z75OsRpm4CA=,iv:RKDNPbjHIX0gXfqythYv8spfq3s46G8FSRikPzneS9M=,tag:w0JhLU3uSO8ObRVu5L4/6Q==,type:str]
    smtp_username: "disabled"
    smtp_password: "disabled"
    dashboard_username: ENC[AES256_GCM,data:Gt4b/7RU39g=,iv:1U281/ZyJH4gxgCGhAbKIe/MUdnlKiSSqKgAcpIhKLw=,tag:Eq4PVtmhrub1sTr2cBBlZw==,type:str]
    dashboard_password: ENC[AES256_GCM,data:KeaG3UUcd8Q=,iv:i2dSgZyWnj2qZ/ovV7CqRqVTB8DiCV0/l/en7AoAGW4=,tag:hs03+ViZtGdxt9+O1TcQ4A==,type:str]
    analytics_api_key: ""
sops:
    lastmodified: "2026-02-23T18:35:38Z"
    mac: ENC[AES256_GCM,data:lVVv5RWhOl1i9efOiTjaQ1YDb6rAKmxQzgRy7mbpRGFf9+hCkuymfYAH/248kbFz6PEwfRsAlpAgKccNduLaWpMuCqvHvUDFwejnJBwpq5t0QZx5GeUkS091QGrJQr4qhrDD3I9CTBXBL4faPSvQ4sBcRExJPhGt50Dny2QcJ5E=,iv:lm4gtxEgdCQL/iXJ4QADW4aUYJ7jlJYxFZjYC7trUPk=,tag:J6K+C5keo41WKX2BJZ0I9A==,type:str]
    pgp:
        - created_at: "2026-02-23T18:23:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5XGugaz6vRlAQ/+KSkPVrimkLqFIOBlyX0eSL1hR47eIqyQdC6sOaED+Cba
            AUHKQDjH1Nq63lBJ8+MGE0AB070ErqA7TfsFjhOHJCLwHc2tVjSP5hQN0xQffuJ1
            wX+pceIajIzwY4hEP7Cdq0yxhqHvJlPq8v6MF0rEkw2ElGvJdILndsE9+3wfsUk5
            0fz4Mzqauda+N3dQv6jLjRtGg1ytEOEP1bh0t7h4p9NP7mqcrIXvbQmr8WygffTr
            e6Rp15ewD1AN0GoDPMmoi7brPLn9B7ODInASWxVeF/4dERX0qJr6G6KDNTxX3VJI
            mSHZkXJ20jeXZVUdvxPr5H+fjzuM3MudHmEKTJYPiHR7g4gZMUjKADAWS/kUWmqh
            UGFhy2sbCm1RsRcTvh0o3WLW9bZpQayTO6MpkOHm2NVVcWrqbBWcGqGNOz+c4hSZ
            mrMk5ikPWfyxz6CMBuJsusoPHj1TnoBkz9z9D6XBVH4n4vdbZ1YOhVo/OinBuG8B
            5h/IriU9/qONrvVg8hDsOZAmpu+4bDhnEgjn8A58t43iB4Aw2rCWrVKxm5rQyjID
            /nyipOkPNfCpie+CrxJTQU+vzDUekAPJG0e60AsQ66waGf1plBYkY1hVCgx9+/I/
            ZsPfPCfEpmmaQTxkn0DzNeR8jsr7xcQxvjxRCy3n+9xez9fDpn/Nf+R9uOzF1d3U
            aAEJAhAJzyqwhMQrbKSwufWoTD27Ei4IaZ26nxuHzc+koUIsFU6TN2ONFJhWRF8Z
            kToAXZM/rA6dIuSWYooiCDOWTo9Tr51E8k8rQWYU/ZWn4ByUgu0dZjhsZ/RPLe81
            hYgo/KJ0x0HV
            =XMne
            -----END PGP MESSAGE-----
          fp: FB5C16FB8DB546BB01DE0ED9DCCC989D57A72B56
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
