apiVersion: v1
kind: Service
metadata:
  name: supabase-db-tailscale
  namespace: supabase
  annotations:
    tailscale.com/hostname: supabase-db
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/name: supabase-db
    app.kubernetes.io/instance: supabase
  ports:
    - name: postgres
      port: 443
      targetPort: 5432
      protocol: TCP