apiVersion: v1
kind: Secret
metadata:
    name: arc-runner-secret
    namespace: arc-runners
type: Opaque
stringData:
    github_token: ENC[AES256_GCM,data:+h9wPGZ2W99gQUALxC3gmZPZrUMiN37309ufj35V/tZYYKzLV+RIGHLcE8tL4nmS9fKm32s6IEVJ6bPj6z49teVNkJsM+xGGTvdQZbWgA8M1lsrXZdcFGFJnyMWe,iv:0WJgk5G6HkLbK+byXVQX8/xMaN4Q9J/qCeEdPJjiQJg=,tag:TR7UWnAasJ/ccoZouKb1Pw==,type:str]
sops:
    lastmodified: "2026-02-23T15:48:54Z"
    mac: ENC[AES256_GCM,data:G4JdCOKK08JynuSDwdbC1oDkGYcwbKEQtagWC0YJgKjaImZkNhKj5LO0uRMBXyqp3uzWwx2U0myl8KXzEkmjPa6W59P2l9hnXyqJYFehLRupkrKLCCj7eyhEPZ+7HOofrg+9q2mMLIA2LBQ3lMR0Is65tUBMEdvCdeR2EP177xQ=,iv:VxdhuG8cH/VeqmecMUygT4tzawf+ohACcMrHIDvnfb0=,tag:0BM4QnjFZRp/Gn1yaB5kJQ==,type:str]
    pgp:
        - created_at: "2026-02-23T15:48:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5XGugaz6vRlAQ/+KdHecS9pwPuBnIVV7VEragEhoIx04/pqG/TyQwpAd4DQ
            3k4N/FqgklN+xE8FuPsZE5tpXS4PWGqXut74kyKWq6xOAJKzLu20/UHfthRp1jMG
            TbA0b68m320S1QCt3yiuSnN+VaepGFS39JaqAmo0VJSlQJrf7sUoHivlnxxG3J5e
            ALH8cd5psO9HPaEkcr2IteVP9UijnaCovmiD4sXgp++Qgw/g5mcZnWuwV/l4Yau3
            +WeE6Rg3XAJMOqzZm7HnjeG/fzG816VZ6uyZiD3eASZW+YBN7A93WGw6dRq0oHz+
            KC1e3/Falr4fAEWHfk9mW3JEAaQekhHatmu8FnzEhnNSooIJoLEw6yaFSvZcJB96
            YE1RU3cWgrraVGS+1ai6u+6zs38PQLjGmDFNT8dj36GLHR8aXTdCrfj9Zuni8vEM
            etncVOXiVemlTl4ZTgnf0AmQQdsk66PA9hay53umd6V9vJpFUgqlQ6z2DkS2B0Xc
            Jebh4iELUqUdZcyMKW6Jpns5QbS/6EGigXpV4DeSj2JEFc+or3yl244vnXHKFx8J
            d8liEJyN5Bd9M2rQhFzCUINzh+EdEkfNvrEB0Gj6V0ObdoBBKn52PSM50DGLBWVB
            Tv17g//eeT4ntBTZLa1nYkEAoU0+/V//PLkK7n3a4k73nJXPI2plRU/8Nw9Vm0PU
            aAEJAhCf9Go4sO5k0KBwvXDLIX1Ow0aV/Iq9hEtyoAQTcmw13ENKg4QNBRqSxvjV
            z7DXN8zD7EJKZPdi35dIV3g95i8+2HNAH8xoeWvGuRWe9J7E5oWQuAAN36VMpIWH
            QSopalFB1ov8
            =QurT
            -----END PGP MESSAGE-----
          fp: FB5C16FB8DB546BB01DE0ED9DCCC989D57A72B56
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
