apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc
  namespace: arc-systems
spec:
  releaseName: arc
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      sourceRef:
        kind: HelmRepository
        name: gha-runner-scale-set-controller
        namespace: arc-systems
  interval: 30m
  install:
    remediation:
      retries: 3
