apiVersion: v1
kind: Secret
metadata:
    name: arc-secret
    namespace: arc
type: Opaque
stringData:
    INSTALLATION_NAME: ENC[AES256_GCM,data:agK4sQZ5YDPjam0=,iv:Y8CjFn0V8O7/WqYquDMkLz2QDVf4hIS6dACmSl7qT9I=,tag:vjNcsn9ZJPNAP/FziH9lGA==,type:str]
    NAMESPACE: ENC[AES256_GCM,data:jBBZ7+clWjRQI48=,iv:gjAfh/H4reDwiwsHyNq3hTiOJ5+wZLf50Ni9EfYEbFQ=,tag:+ZTJT53XE91TdljIjtF3iA==,type:str]
    GITHUB_CONFIG_URL: ENC[AES256_GCM,data:8tsltv9hZytm1MtpXo18aH6WLQwveKq7xh5UkQ==,iv:h2E+1wBprroZ6HsaxmfHnzaigEkH22SKm3PFtZCkAfY=,tag:usssheu/WqaJm5zlRo1vhA==,type:str]
    GITHUB_PAT: ENC[AES256_GCM,data:XGBoaNAz2xthsgtW+Hqqxx6eWokTDXTLFo6wS37QEJSxuQ0uh3SC2ZMHVHfb+nkp7/geXQjkZuMCNEhvw3b2qzanQvHUXNPkmdMRPaqZC07VBfeufnMIDBiLe8kZ,iv:i/Ps9QsxYVcnQ3mcY/mUI2QBNEBSZ1+z45Oysv/zr44=,tag:Gm8VVTpe2maYk1pzuTRqZQ==,type:str]
sops:
    lastmodified: "2026-02-23T15:39:33Z"
    mac: ENC[AES256_GCM,data:IyVNkcxjg6OjNfcoKUn9u3zT/dNd230ErDLk1dbHTQSiqLTKAuYwCyzLQ/AfP3VBdFXvUUlU0Qny7t7bPVUzMuyeDNz6lGIBdxG52OS9I5cn+K88gDgizMWkG/fx7zTqFnJXuTiGTISqvYKqgK6Kem+fK2xj8KZjAEJbX2VlxJE=,iv:GymUbDzEirPaXkI4xqBXbHAJtwWdNfbbrHQiFfj6CYg=,tag:yCNHAQpHOsfxv4mM2Y0wAQ==,type:str]
    pgp:
        - created_at: "2026-02-04T19:06:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5XGugaz6vRlARAAq8pbHZ5z8DFzDW8gU3mh+e50RFN7cQfr3tPhD5lCARvM
            jVBF00K6JDir2OEUHBptektYin2RLswpD5AyZo9mMg9tz1Vmq3oBtqEgLAz/Knps
            4wxGzRtqH+7XY+y64PVyd7uxlId1BmuaqFnek6eTWYJNkuGfiRWApQ0jHlOQnjTD
            1ed6OVuI0sthDs8O0CtgOH/ZP5l4n2C0wYnpXVwOHR+c3bLosOU9rxIeL87QBcYN
            RXrqYIQnyI1iB2BPXu7D+poF2kCAUjDTc0GgK6Stp9wIYSeWk3vtcc7JUm0gvupK
            3EN6+3qkrPcsW2YRmC6Aa565PRMcI3wThEPZ0AWx56dBzYQgvwcDdUx18B0yf0zS
            CHxGqzt5P5EKEogggbhKxO9rS9ttNSKMcI9dgYq6zV1SrVjzzHPuDe2DR/jt4utN
            iMeHoOyi9JTD6jIPMzQhMSKDDdhR/5csNa5aIXlTQQd3Y9GdOX/05DI65xqK8WdM
            fjH959+um92E3Cpfweu3li4uLthBXZJWcP/IpsR8uUg+RpsYR9DL58yUKJauLwJX
            slnC9tShY3DKnOxDWC4wa4/CTeiVAfyL0UXZYu+SFqJg4MAQwTXbHmQtAzDMEGWo
            CmYBn2syewwceJcFTf1pGLNyFu9MqqE3ws8vq4x5ggQcvyOVPInD2aan5kH9HzbU
            ZgEJAhAB21hS1G08VGCEh0SFiFvv0hLD0HBjBYduBZEV5EsVNeXW7l/1XoemdCZb
            xuUCYqTzaKDcNT8NZnT+UMeWUgdMFqOFGs6UEEEynlJI3GiZJAMgwRgAcETFD4IK
            +OQXjs6Tnw==
            =Fe3l
            -----END PGP MESSAGE-----
          fp: FB5C16FB8DB546BB01DE0ED9DCCC989D57A72B56
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
