giapiVersion: v1
kind: Secret
metadata:
    name: awx-db-password
    namespace: awx
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:3A6A,iv:+NO6AJWmO7nZbCd2wn0U0FfhqsnDT21YsSWB2PnsSyM=,tag:JTBwvCQULOXK3LY1eZ/Tzg==,type:str]
    password: ENC[AES256_GCM,data:5LlwVPug4og=,iv:FRyfVRxuAHmbYBp8kGRySdEOGfRtx++fjE+euMdV3lo=,tag:y0FZFPRXKtUWXmFODgzWeA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-08T23:50:52Z"
    mac: ENC[AES256_GCM,data:z6GAnoXpJy8RifWwLz1cqTKTPzljv8oFznzyGuKytC9EfxhjRlvPXf2JYlXlQUQ2drCWfMi8mZ7BgyfNIlkmoQqLw+cTUJ8oeOpAWPQF7bRPuePEHfH1tCwiFRE+2bflzPXKhQz+3EG+CCWOFzPD+r2+GkBQrtIPrUGkIbUjLSU=,iv:qHCUyRXSilEcsXcGmRGqMwkfgIn/EtVTLL/eUW28pos=,tag:dKiX/BciuJpwQ8FvlwCAsA==,type:str]
    pgp:
        - created_at: "2026-06-08T23:50:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5XGugaz6vRlAQ/9GmpYAOGxQDKJyYA7KTJ5Plt0agyPac43MTeogbU2ByHU
            MdFWqwy6RYVc+ICapSNo0LXCOcEAqkAo0wzGfwK5YB3DVVWDFv4sBQt3llSg+w++
            Bzj6ts9M3QBmTNBPNwzd00VSqZoN20OiXRM0bh6lC1jYzJ499W1+uubiBqCpOrg3
            sux7pi8BjvyjsaPGWc3tlBZ3opfs5ePTqk1K9xHM2Zd1/UfFF/clFMm8KJGyOG0Y
            xBvXZEm3gKWQYOaXNK+mEyFqJe/AwSRpp/10ghymMGd37AfosLXR77GGtnSmWJWc
            mxhwoxoDmMidnS383lvu2D+o/KK6PWAx28bAnCHbSwfz7xj4wMXp+cAQL85axLfk
            3U9hLiHA4HjEszBnqppZZMQ0rPcmOLPPFirRxikWcFsDNayzDWWhFJBseh9Jnv+E
            CWrLN73GJsXqqpBMgSYHt7OnMgDcIwhZYKA8QMNbgPz6AwAeBHkr000Pu3cfQi2w
            2U4aZy9MpUWq7dmkmGEgS8QVlKBsvfT/06PAbClRgQ5VIoHySe52hOtK4+BvR96I
            4t3v94OJjRxdYwA0HPfPAx1hBghTfWbB8upYZY/Lk+Lt3jmg7rKZIWEgqtj3kctZ
            zGNMKH0DX5hMa+q8HZXTpDxofAzOBHEmaZ32KcPJ1GMeIS8hy7+EEAYYR2gVlX3U
            aAEJAhDKZ7dcmQMYF2yYM1iLfeq0YHzU9WyZ3oxJYOTWLKVKbSckduARmMs+8SJ/
            mZIgTPAolCKRdyORDlOqRPThlPtWipEiNEC5tWrmP09KedY0LDXjiahwlwWl1vf6
            6/z0ZPaYzubM
            =X+yD
            -----END PGP MESSAGE-----
          fp: FB5C16FB8DB546BB01DE0ED9DCCC989D57A72B56
    version: 3.13.1
