apiVersion: v1
kind: Service
metadata:
  name: diaper-party-tailscale
  namespace: diaper-party
  annotations:
    tailscale.com/hostname: diaper-party-tcp
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    cnpg.io/cluster: diaper-party
    role: primary
  ports:
  - name: diaper-party-tcp
    port: 443
    targetPort: 5432
    protocol: TCP