apiVersion: v1
kind: Secret
metadata:
    name: slack-webhook-url
    namespace: flux-system
type: Opaque
stringData:
    address: ENC[AES256_GCM,data:l5+vYjeDgey6HgN19ID6GQ1RArK2/6uY7/DJpSxzX8yjEeqZJrvlcxCuAejXaiyPQzYchUuhsF0vlDb54v8tBQN+UgSHatBJHtt5eoE3rT5N,iv:BqhJyGwk+HGWg4fv1ADbG3Pb0AZjA/ZgxKZfD4CURS8=,tag:zmK4FQMM1WTnyaaxneEs9w==,type:str]
sops:
    lastmodified: "2026-03-04T17:24:34Z"
    mac: ENC[AES256_GCM,data:kWSFifK8rhnKYwz7tEG/6sUo+OV0hsEFGMo879E3rm/bQRX9/s4EtOaRh2QFwTP38AA2t1hcegXXDy1x3FI5A+dMGtanzla39SlxczGnY7JZQTHYGRUYv/3s6ZQTAM5FMFnmhJ9wwujpnpO+CWKoPZ5js2Zwz+N3VVyV70diOXI=,iv:Q4shaPEIiBmPv+JwJH7hvdGJDGfaib+v1mI1dsmYGp0=,tag:jCF8hAyDFdOCWKxmfEzhmw==,type:str]
    pgp:
        - created_at: "2026-03-04T17:24:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5XGugaz6vRlAQ//Zs337GzF27bCV84Jt/u12sUUliEU6wQjIz+7BKk66caS
            SV4aerfwy3+KwZUs7+YcoqTm6Da2adZ+abQhqiMvPuliscAyC/Ca+8lAfYcqvSdm
            64FsWHLUWOQOuRjZ+i1PKTeCvKnoLH/wauWkwFoSy8S87i1QvgV4BEygWGGRfrhc
            mzqcK7NarWFE6dnKp0hnYcsDv6DjCPEnbVyQCpCPU/VQnRKxLB6E6f+LdCyu2WEc
            P6RzOrfXKItsXXta1rv9C9Wcy/kwdsBnCH269VhevxxcrDx6MuWnWMNgTY1YZzsl
            J/bOrzZ7aDiM7cmisVGyVrxyrFKUcwohLBsEfyAdYRGsxDQ0TEXXEi5M3m5fJUaM
            iVmxXMKLJHWj3nrt1Bh8Bxrz8MaMxO8aPZIkNQrfmoLV5JiZ5q22cTX5OFJXqJKf
            uAqaDphRblaHN3Ig6dVB4AykcLFC/TuF4Es3nbDJZ1EHqTeq2Thm08QVOOBzKAXI
            9MQEYCzfJW8T88Z2RJQzJI7b1HnwZFEiaPqDm/+jGpreGwRQoF0KVTtX/LCikQzI
            z0NfuRQepjD3o2Atg1WI0fL5sTUbhP89e8fG8VJY6kSEmh0CBrO7apb14zrcul6G
            L1DGbfKzkPbo8BbcOaTNt7p8xebdNnXKqug8I0U/HiA3N4esyCyCFwNRvryGU23U
            aAEJAhC7f79s90c1iFhiaH3yOSYg3EQ+rwxLDew3ZFcVts/xdsupPD5qhzivsC1G
            jsA+RcuqZrzcko+Kr+J9OAxnGwfDpOH6EhoWLJtOGTZF5D0h3nU8l2UEfeoPoawA
            UtLDi/9gBMZP
            =SJ9w
            -----END PGP MESSAGE-----
          fp: FB5C16FB8DB546BB01DE0ED9DCCC989D57A72B56
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
