apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: water-taxi-simulator-ingress
  namespace: water-taxi-simulator
  annotations:
    tailscale.com/hostname: water-taxi-simulator
spec:
  ingressClassName: tailscale
  rules:
    - host: water-taxi-simulator
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: water-taxi-simulator
                port:
                  number: 3000
  tls:
    - secretName: "water-taxi-simulator-ingress"
      hosts:
        - water-taxi-simulator