apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:77u+KUa+rkZy5mhbZr1/sxp2DgN6TAIfAgiLGaWO8Sg1JSaU3bmRpfu3HG/UL8a4/0ZXIaI+u0+S4ujNY9ZWB3DRVDCAIonrQmaLeGMmrQhLbHfHWwwWbykrZVCc/8ZBMUutU+6Alzup+RczFYTc5Bb1wbbDwzvdhfILxdPKaeVHdkOrFoIOfgqum6WvkqrII58MZyQK3Q5H1OPdD+FonQq9GBGYxvr26TlfVlSpi7qtB7fN,iv:b/c75WY8ryUVtdeXHB6GweXOPMTH4/EzmqnyJKtsvnw=,tag:nAIpIvg1C0zobf8/1o8aSQ==,type:str]
kind: Secret
metadata:
    name: dockerhub-pull-secret
    namespace: water-taxi-simulator
type: kubernetes.io/dockerconfigjson
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T16:54:04Z"
    mac: ENC[AES256_GCM,data:LbZw9lSdzFe5+B+rt0TtKrK5CcbUrn8yagZ03Jz3S42L3UlUlQ0lJUsbq+cHfJvGcOETZHx5tbW3HEHvuedHhMCCiLz7xDJTVzwZ+6LcG/8NCRbgx8n+oc2yGuh4nVik/TCqOYvCtpW+ZKfrD+ZXo0upBtKK/oHpx/0RuqIRHKE=,iv:9SkKRkSGmwL5UWYknwSH2UA2mshehn6MRWGJP2x0Xqg=,tag:M+O/CiOR9ps4iKmnodg45g==,type:str]
    pgp:
        - created_at: "2026-09-27T16:54:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5XGugaz6vRlAQ/+KvQNyzkXU5g4MslC9WvWx4CNY2YFxOKFIBA9SqPHmpwe
            L53Td3cw0lXvJPuf509IMZnrYdxvp8qpRmLwH7Y/yVov9TaW/bjCPHCPgvUVOKgF
            X+qe8WQLt2QdYg8mWSgRX6yzxWz8b6SGUpAiwgt1VRwfHiF4+CSE/uonTypDVgID
            rMqIB0R4/G1WhAdNcgATQOMUE9YACCxsOnPBUl8WS5a4OmIE0kjFAvgmXlk18Unr
            nOw8mVlmF6D7mLzsHCmx/rDE7ZzdZJak61SfH3h2Tu5kQsKo0awjZu23wB9fVSJf
            BKBnOHvuRTkdf8wCb8X4SKPehOhi2CLJsz89Hu9500loXg+TkuxY1CU9VDuHD4gj
            fipeNySQPNdPYbY+3wd/1Waa4PUi91oo0OTs9MrfwzGDGRpvxRoH4v7tHFz2ZRNw
            5Z4gJiIbVCs+FYWXo1pVCQBQaS6D4R27L0p8RlFkAXC9XV+8SNHcp3rCLYAAxNdj
            uGsgt1u/3ABe9TN+eLfyySgq+zLvrn732aAS/UrPVfGjCKHTxs1SNb37uEUuXRyV
            r2/H8iHBSGAcPTqLlepZHrcOOsy2BcJHbK/F8eZpxT74E5Z0ZSeGI5QGuXQDL3aK
            E82XLVAzzwphOYLVupsYpMlzwWk/pAwjJxy64ofod/Dk3uIYnAcy16vt/K00hxzU
            aAEJAhDO0z7INX4nThrdVjcDdmpF00W0z+eIRgKes9I928CcNY2T8q2mDssNO+LS
            r21Or/GOIGQkogsLjn81U7qTPfT4i2xLDGZ4EYn97avyNuLYCTBfMbdo06PtZtUG
            67hVnAsqEb5N
            =nkPs
            -----END PGP MESSAGE-----
          fp: FB5C16FB8DB546BB01DE0ED9DCCC989D57A72B56
    version: 3.13.3
