apiVersion: v1
kind: Secret
metadata:
    name: water-taxi-simulator-env
    namespace: water-taxi-simulator
type: Opaque
stringData:
    NEXT_PUBLIC_SUPABASE_URL: ENC[AES256_GCM,data:VhT3+HCscW6H0z9uak1W1NksTJE3Kqbl9ovRoMUTxA1QEpb7K5gBXA==,iv:pUVyVB5R8SpqdcgdU9n/Gf7jNVGjazDoGTsL5a61JC0=,tag:7UvDbKlAPbhgMw4wKDJldw==,type:str]
    SUPABASE_SERVICE_ROLE_KEY: ENC[AES256_GCM,data:Mzbr9ONUOlQMfYHlnqRZK/YaLKlUgBSlfwmj+wg7XuTxMZP6to2ccFo=,iv:WAKWxe5ld0DrqC2x2x2ZzBqOkaj4EGJXSUC/kcLArFs=,tag:eLcQ6dm5MHMYnwhwT2Hepg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T16:50:05Z"
    mac: ENC[AES256_GCM,data:NqaDOsIw+ny6Zxjf1YKbUiGcbCgictepqt/UnYHyx9MFMuNoMnIjpCdkHGFbYk1ywO5EWcyuD5XlO5eC2iM8sCdx8BdWgUFKMrrS/0Rtp/XUI6XTmjJkOS/dbQ/PWqKdw3a/J/T8ucWGF13VEQUIsv2BoshBd2gEuvrU9MXZ7ig=,iv:XiZRdw9licbGE2wEfBJfzMVdgYsAzMTK2yuaHXBXlKQ=,tag:hu2oeDiPmsK2dJlo6mnMIQ==,type:str]
    pgp:
        - created_at: "2026-09-27T16:49:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5XGugaz6vRlARAAnzIFgy5MOsuE/DQtSrWOonk3DE9tsQFT7PcKNtfNMb0R
            sa7rHaLQlK+sa6nm7d4YaHo8SZ98S9CBg+vTP2zRuc4ARJYwGcsfL7OTB7dPNEUc
            JV926QUmeCLLyXkyQpMHPU1OJkz8/bO+KM2wDbxgd3l7wKt5FXCP++ZrYPJnN3Qb
            4o2IeKYBGFFpQ3VdFgcLRcWJFhCMesZDkK/Tqtr8FU1ijOVjD1K08UcLKAlAVUB7
            ZHBJ/jUVQpnD1R+rHUO/70K8pPFYXwphgkjsnag7LwCgQn+BdRd639zywB2cGYud
            qiK+GIQbExeiyNjC8/Vcb6xoemswDVhqdA58xUnlIqc6ZX4UuqtNVghbzfeIgsLt
            ick+8i2Gm6YiX8SQE4lN7ksnF86w1p1MH4gmdLQmLF3QhEK24sJo8XLUpP7e5CXD
            en6DGFRABltTsF0o0SAVhEAuCIWX44yFhx7UioOROEHsm8L8IWSAdZaE3sOBOIAl
            hatWyv43gY53DOGRuv1feHB11L2//Mija1p4DYW/mkhydXxL/3X9JyxgyieQhBf5
            II9NTuGU28e0DKob7IfQLYvsYA/Xh058siwpAQ4WBVZwnZOY9G/Ip4Xuyrqioo3L
            UqxcjXF58VYFjCTi//GRHwpoRiHe4UQ3n+pmqqkCKN1PLsQPbUOa6FVCwQn5UpPU
            aAEJAhBKiZw58XSLw2w2b73mBHzDhxXPqVpeM43qwlnQJZ/3FpvAI2ZlmVRpgp/p
            1cH77dXPHjkivKCWZd+8ropbQGBuwflSNh7qaxS5uA40vZd3BuXUCIarwzjkIeDz
            ii1jAVZO++qs
            =RHVo
            -----END PGP MESSAGE-----
          fp: FB5C16FB8DB546BB01DE0ED9DCCC989D57A72B56
    version: 3.13.3
