apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:MFi1AoYUtARpGu8kzT79uVxTH4jQGhY/beAAidwA1N9XtEICnDfDzsbAUBIVOXtmq/KwMP8GZz9jQfItlzhRbk4FPIRXzlI4za3J2FrvGccIBgwI6F+xi0IKKOy8WvNqTH5pSHQelA7BEvCi+4JSV7r74zUyFmAy8bnzjNeQbJfLf/M4csQ7/p0++BLu+mOwD0juxwu4TsQRM+6IaFkwRXxKuupwo7tsngr+PIzVzCxG3IuPtjZPCfmcWok/cHJnNd4DGcnVvZPcguzPEkYgRJEkw2zYdARhzlYCyls5+9KjQy6iED9ud69lQ1Wvm/s2,iv:WOSWcYh8u4A1cRWq3Wb9SfTzP63E0o2+bUbv13FN0/M=,tag:8aw/M7Ums6psKgUUM8PQSg==,type:str]
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: getajob
type: kubernetes.io/dockerconfigjson
sops:
    lastmodified: "2026-03-14T15:17:11Z"
    mac: ENC[AES256_GCM,data:GLd70cp9DC8ygcnVzHw+k6CbhGeuvhnA5h0BjwAD9VCyZNWLzbKSpkbgpZT6Zv8FO076TBT4Xx5TyShmfTvaU+W99xucQ3xr0NQKPI02Ac3EyY5E5yF4EpH+i/YvvoFZE+dYg/C0B7qqKvMGWRTeHY/dDGm27KefYDC1gR9mflE=,iv:RpTL+YKIS+CrsBFfuGAk7awPDRGfdNx6mFSk7A+CrIs=,tag:OrOmzLN8RmXWrSbo8dltGA==,type:str]
    pgp:
        - created_at: "2026-03-14T15:17:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5XGugaz6vRlAQ/+NoDJRbBHStPoivz7ZCzH6mNfk9/X+FVoqoqkIJQG+bdj
            mV+teaSeRgFvrjR2W4Io8ypmG57KFsLRmxAgyx6tPGITrsMw0rtVyP+6EUFkunTr
            38JSvJzAEi5M/UEUwfipgMABlZyhWF1bSXD/oY7z+At7T05lJ/IsiJdpCHF+U1x7
            flDvd8/xJlMFkzWqcdwSg/6ou4GD7eDGud/1ag2SIfDgp+HHjrGX4CHu+urIbLGM
            sQ2/shQJeePWbHr3x0kg9rFaTHrSj2IJ5irUsfP9HimsjJm6pACv+rqNh3LnapDN
            MVWxWq/Sj+VN1xLYvrfHS/eTdrMb449fNNelstF5p7OvVcbtjosOe1nq5xjxgr82
            45zDseU0I/yD4Fw+g6Uil8PBP6zeP82Iy4p4lNmw/26XV17RMj22z6YpE9nL31IN
            TQ2cpaawTS4Jvv/M4ws0bzbtWtWmprlGAsa5zufSS73YX2lXba8mLNCGsiGlvEQL
            aBO4fp9i2mHvXnZr6bnFVcXwtt9I4MWDEn1sw1/1HgaNHacUiIJK5Y38gkCU2GM7
            Df6pWqsYu0JrQlKxCwX++jBuFzmywm5zYPrvS4mAXGD4uwYx29x/1JCmp/b7IbOm
            o3mi5fiMmVdcoJB/J3Z4Z/8NpxeR9n+n4ELPCC8ULsoVHioCDVqVx7mouz44jCTU
            aAEJAhAHek1KiI5txlvnyFechHsmxclztGYpQKukFwyj9Xz6+A9uJM7uQffcAbdp
            9Wk32FEEQvDaCwWcXldzimLNVk3ovoHIYw2uxpjAqXaWkvv3iIGVhcAKar7mbLxj
            W8EyjpweN37X
            =n6li
            -----END PGP MESSAGE-----
          fp: FB5C16FB8DB546BB01DE0ED9DCCC989D57A72B56
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
