apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n
  namespace: n8n
  labels:
    app.kubernetes.io/name: n8n
  annotations:
    tailscale.com/hostname: n8n
    tailscale.com/proxy-group: tailscale
spec:
  ingressClassName: tailscale
  rules:
    - host: n8n
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: n8n
                port:
                  number: 5678
  tls:
    - secretName: "n8n"
      hosts:
        - n8n
