apiVersion: v1
kind: Secret
metadata:
    name: n8n-postgres-user
    namespace: n8n
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:9TO1,iv:0LT+OVGdYWTW42SzsGHXt//C+FSR6MS0mRe5iHMzztA=,tag:OY8/8nGzgZMN4nMF6YpR8g==,type:str]
    password: ENC[AES256_GCM,data:xMtWFmf7wow=,iv:x3fxiz7qq1N9+/IdxuiCCP3+FCIpgjTx/q2VB/+QYZg=,tag:c+ooH+5eu+LbUFcEmUmsug==,type:str]
sops:
    lastmodified: "2026-03-11T16:05:22Z"
    mac: ENC[AES256_GCM,data:mmTRJOEReWSQbWzpSVouxlTIgRYzdmJCeKOh+/O+Vqul24G9uyucrcCP6kHTnOcC6mfdalIz9dAisXiWtt6DZMThdJFUnJ8CwlXdvcbip0oGR3liFnDmrHTW4lo6PELMslpVenx5U89QavC29hYBoGhs+Pm357ixXE54IOg0HnA=,iv:pFlthief6WsV7LwhHq5DR9QhmcXsvHjf3R/7FKXVd8A=,tag:tsb3FDJ8ysVN6P5O29/gdg==,type:str]
    pgp:
        - created_at: "2026-03-11T16:05:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5XGugaz6vRlAQ/7BCbdwCOrROySYGgqrg1DEc4G/eBXHetwPRN39M+Vqd75
            We5k0jHuNYjBOfm0QaRy7xMpA/3hYHxH1mTIvBQAnt0j/8GJNoMe+BzwvzUdfKqO
            oS5nWxTsAGhWCdTUfhzXgSFacH/qDbXQEv64wYaYs2q4txKp7FlX9e4hap6xMdXt
            zug/119H9NTr6xOHWUDZzG+lAHkBjmpZQKP9bSfyF7W45nykpZd3E6yVLxxZggLt
            FyUH2sKFsi3u2jxS6JI35YEPo7lQo1It0ilbe5HDrrssGAzayHlj3B6NRD4zKMRj
            I85qAjIT2QzsiidjKHYHJutwF4gElN4M15RVJ9UOMSqjDU2GJ4M28Hfs9obIUZ2C
            sXvr+tT4RYyxEr2u0vFMRorkMMHzeMZuSQ6XlUT6AKdJp43jyirhtVvSXQexq7vp
            L049+7eUjw8FE1rsu0EPozaTxcBdFVcXj0FHgepAn0sDykq6+wf7bvxS86B3gMcH
            WkL8ZzM0KTIWX0wdrN9Sw0FTtHxIWBSufAaGqGMuNOi5PCmOudHi0un4JYxK4Jgw
            FFo4abXLsu87cA5DPHn4vYv+STf8sniYl0rSghpy6rsF9dQOh14uGLJlnS5oJF9s
            G4xPrDu9LAJrx/leQ5Jn3O5VwbLay45jSUT7EJEt/yIvo69mDO07H9W/3ZmqJhTU
            ZgEJAhAbdIAJoHxwyccL86ZVhw6D42zrxxF6x51oVYGmPzSrjWcEo/5M3IdWVH2g
            uWnP42RsFZmq8aEblOChhzoz1WJuwFDB2gZbbvNnNnyfS/DlmFmfMQ2B5p/muGG+
            M0cOQ5mRiQ==
            =s3hV
            -----END PGP MESSAGE-----
          fp: FB5C16FB8DB546BB01DE0ED9DCCC989D57A72B56
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
