apiVersion: v1
kind: Secret
metadata:
    name: n8n-env
    namespace: n8n
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:Q97ta9O2ubCtav3AX+O6N19pU2IG46t3RW/Ug5Nd0/XoD1LGu/MFTx97+Q==,iv:+VWeoKyKA3FMCKqpkBpqs5kI2P/2g8fEUTF3bvB0wCo=,tag:Bsl6Kf/3TWNIlObdrVSXlw==,type:str]
    WEBHOOK_URL: ENC[AES256_GCM,data:hMnYTT4QslYXAbmd1jtkVSgB0EQcriIotzWQjDAupIc=,iv:qV/29M0a+vwgB79wBujia+yWsp9vdJOLjy0lqYct3BY=,tag:sADRJbxkH1UMFfZBrCPXjw==,type:str]
sops:
    lastmodified: "2026-03-12T16:54:46Z"
    mac: ENC[AES256_GCM,data:J9HYjb+OT12plPiCYHu19yibMB9au0BntSvOXHf8SOLorbWuyOcTFwRVvaZUyHpSRfe2ONyyYrgpKEDkDotdybHd/3jRVFFGuNOrnWDjONKpVzhqzlz62fJQcF+jNe8cCRNKJIGHf0wRLChtNu6XMAk4R+bfu1WltaSi24ktAg0=,iv:q8Oi+gNyeKSmq1mUFLUxn1/FrfSgo7GE1ZxymPgYrcU=,tag:T3jmJyuQd5KPRNffzQArTA==,type:str]
    pgp:
        - created_at: "2026-03-11T17:16:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQILA5XGugaz6vRlAQ/2JxOXYxSexkvNTOb9RVawirsS9IBNUDbc2dfhrXqwMLWd
            +K50sjgJpoN1/gtpDQ+qBAodOxd6OQgyOspBLUxXTLVjCp6EP0vUUbqp+uhMmQ2B
            z27RpAuEJumkB2ZlAM4INtHG2WBa8MlOmak4B+TC4142hBgxc6mKKh4Cn3EqIfr9
            stdbfmpJBgf16+RUWCNfqXR4LL62J3jTpUflW6NKHf2NwBf+HcbTarKOxRbXru+Z
            dutU6EJlAfXRAwlNssbFXD7R/ISgmA+uA8Dc0pSwzkHh/x+qbv7st+Gwp0ZW+vks
            Bvnb1HfaqMbVdwZf07hu8DSzA9NNXC282Ob7MQjM1HwWJNVhfd7wOhjuPpHxADgt
            EoSoCTstoeTg6hYYSrwp0D2EDe2WziaqHCXsyMrNYAcUib2sqRFncOTmRHYC+LuA
            dPCn12XSZtcyk4AvWdVZmn4in/z0RLwMR6oNJE+ZBb6xgj+sS3vfjoyCo0b6mpUY
            HSTAKCCzFwiHtcMDWrRgQORIw8+lDBpo5l3IF8xzjlWhibvHrplKpzMAkxAPUWiV
            3PCWIEE3uoCSRsA3nx/9CGMIASKxvcfT3v97nQvH61U+i7B5MMCh1Q/XfbwnO2QG
            AgEAJRONXoaQjakRlueo4qsessHOCddfnb5lSCRblPr+Uz/fv2BEquTXdghiSNRo
            AQkCEHFPxdTArEsFOStpfz0IsOa0Ji1LoL2uXoSCs8wj75j+xOlRA58M3LPu10zC
            p3+SOmtP5rw7COT3pk4zPEb0r/Y7axDoAz5RkphTDeC7S1NJAJqp8HJn16lW6LfA
            tX86LSTjhb4=
            =WPhY
            -----END PGP MESSAGE-----
          fp: FB5C16FB8DB546BB01DE0ED9DCCC989D57A72B56
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
