apiVersion: v1
kind: Secret
metadata:
    name: n8n-env
    namespace: n8n
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:D//a0kI025xShQLGtimXic1QXG8SGGXfv6tDAIwJ114zQqHu85FkkXKwgwg47xGLNj5CRNLAfu5miEgkmU0KiwAG/DPKTuo=,iv:B3Ro49skGIgKoFIFNpXc635z0misUyr+Yd9WGywrrxI=,tag:AaYg9T2BnMHBaHXbdlZ6YQ==,type:str]
sops:
    lastmodified: "2026-03-11T16:02:04Z"
    mac: ENC[AES256_GCM,data:BVu+EIvELMRbxpawFiqCX68lSYFao0hUV+7OG+fEl+jDkpD5ehrujpA4UWayjjcKIP4iCyXPDwtXnalqs74NwD1vhux8JGz023qmjZ+sUPU2k5KQmqsx/lVrdGmJyWA4N9Qqlye0aRyiEgf1LJB3FrUgIRnz+x8uTMN7HJSr44E=,iv:FknfXhHfmDppa2gwWC5aqznHwLqnm4Gb6n7MabcTIBs=,tag:h3I4SAfLQvrvKWjnzGtn+g==,type:str]
    pgp:
        - created_at: "2026-03-11T16:01:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5XGugaz6vRlAQ//bm0VrxCgd3/YHeAga8NWzqdKGLDaxhFnVOxFXrbFSX0I
            1Fe84qOEI4KNYMhSqKC0cgzEELptvSX7qqxLrSHw5JNtKVdxTPwNoLw37XiB9m3w
            VI8p4RxFO6vLUh1p5a400mp7su2wLBJtqecFWkkyPbWM+m+gpLq+rfZd/ndQxvbF
            VcVwAZAbmNsBzrd+ixxxwmFWWVdkVUwmnos1MMgRxk5XA4F2IWfEadP6nD6ItVlB
            Lb9sDmO99fok7tFHv0jZneqoyOFePli3fV8r1326QzcHlS3uQgrMTpLG3l9uRuR3
            6TJ212bPlPlp3QciCkeyU7pL6Emio2eB32Wlj0bpmd8fZXHoM1Z3KjC1sM1R2cWG
            8x0up+ORQBauNaMx1ktyFpwjtJJHun/aTjZWDNR6AleENjfvztERaN9kAWtzAX78
            22g3AyyeJtYcONxymiU8AtudHx0Jw/WzrseGz3iLdfTidQLPueJBNabG3/PnJ7dW
            TnteZ37XD1dowRh6GUclmMbp4i4+sO0rDK+MwLbgEz37C0onQnbeaD/fymP2VY9B
            ALKa2liTSWnh4Yo50wzegt+1V2P5KYaK8cdH0D/xudhPlmkgxWI0RbOpOuVKR9ma
            HU6wiOzAmYDkw1Jjw2jmEsLlUie5T5zd9OLoWnP+YYTxuiQZp2J1Ov8Nr0cx0snU
            aAEJAhAd10aBnll2HShdY55HeqHuwsOqUaA+fZxFlnKozg0ovUemH/ivIx3jNUbN
            ZTdMivJVNQ+HeMaDkfjMWiBd6aPs/RxRBCeBLOZ/4g38IL7scgfb5B1JAsO13cVI
            sL41P2LohYWJ
            =lZb4
            -----END PGP MESSAGE-----
          fp: FB5C16FB8DB546BB01DE0ED9DCCC989D57A72B56
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
