apiVersion: v1
kind: Secret
metadata:
    name: money-match-db-password
    namespace: money-match
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:mT6GHHhRtSpQ1+I=,iv:hBXzt/jyQXkxPLOqtSJVI2iEdnudVrQxItnc/pqmH20=,tag:04bEiN5J4WK4aoJ246vX7w==,type:str]
    password: ENC[AES256_GCM,data:p5WFyHLVdCg=,iv:ro38/ULmoxuYJgdgIH7l1mDQRYfdWMarhAgBYHw6FDA=,tag:7OzewI3bi98x3NnPIErUwQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T17:21:31Z"
    mac: ENC[AES256_GCM,data:p37AavFGobSuastGlgQT1he6lgOdxfeLBK6AO/Q9yTXlnWPv9zMHOJxCd0Skoe07caOZv9a+qgV3NVd02+e3vfbabFZwB9mXlYC/mnNxWVB5Rs7ydT+XqdbVSduXJ3IB+86Iyd4hQWnETJyfl+HOzi/QLO1ZhpmMK6Gm56hTdCA=,iv:bKAVMiSatf0YFrddJPbs+VJuirxkNkKvr/7YiBMJ2gQ=,tag:2ELvWSZ8yjgoAxYuw/m9jw==,type:str]
    pgp:
        - created_at: "2026-06-13T17:21:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5XGugaz6vRlAQ//VqwZKHWIh+GaTKVij88Vn1DgtZMhw1jKQ2VeRtDOOO8n
            67iCvKWaxdcUl1w2UtVcYd36Jne0vdRj8ZqL+DxqJFOyfczlm+Ze+UqEnfSWTtwd
            uX8pq6QesvWdhM3oBQdQIt+ASG9riLU48prPL4z0b0WUmvafkiBoGgxDMJtH1ki9
            xuCarO4H/SNjjCZRrOC7m6yaDu6xEEKS48EV0Zwjhhb9RV/b3x/dB5jdhDGtq6t8
            +WgAQkuJ7BLpJKohYcqlA3XhtTTV294sMwXaw2VA3LFPxguazLCkxcr3lozzhvGV
            z6lz+O7AyOHmsIMAYVxCnG3+cx2BDSuP+5NXlWHFMcLiYf+dEmewpc3sEbX5t/MZ
            h/0F6nbQW3mn1BII9nYPGP7RLsRwWhDsvde0fld4VGMW84NIbnzs/2UTcbh1pLOD
            j5uhCqSsiCSiVZ+uaJZb2BzW+Zdi4ElqLtINNoghab/2qclCQ4gICSO7EvLZsg9J
            RtrfDvVnz87gAUiAnnhbbB6/R+j63BSrmrEpUvBzLcMx100K36Mosdu33IuRU6PY
            hjUWNXYyfbphFJAvQNYJiw9nC8s3l+f4D5UFHa8hjYWriX1z0z39ME4nN2RNKt/B
            ntn5y5ov1SsU1+pvhGLriqQYpLOUfglpQtKtJVF+ssMpKi3Cc9gNwd7Od1/7+2/U
            aAEJAhByQMfiPX0k+K9/hHMpL7sPCrIQjPBKEh2qGraUfr/P3UmEBIe+Q1N6AF1w
            gjTbKJkg0w6hnJa3x3GwGMnRrMXPF9apvtF5VygdwPG3YXLDCsXAGWvlWTpzrK1B
            jsZHKkkk8v4d
            =gw2E
            -----END PGP MESSAGE-----
          fp: FB5C16FB8DB546BB01DE0ED9DCCC989D57A72B56
    version: 3.13.1
