---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-gateway-api
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/clusters/infrastructure/base/gateway-api
  prune: true
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cloudnativepg
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/clusters/infrastructure/base/cloudnativepg
  prune: true
  wait: true
  timeout: 10m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cloudnativepg
      namespace: cnpg-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-tailscale
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/clusters/infrastructure/base/tailscale
  prune: true
  wait: true
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
        optional: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: tailscale
      namespace: tailscale
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-tailscale-config
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure-tailscale
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/clusters/infrastructure/base/tailscale-config
  prune: true
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-metrics-server
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/clusters/infrastructure/base/metrics-server
  prune: true
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cert-manager
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/clusters/infrastructure/base/cert-manager
  prune: true
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-longhorn
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure-cert-manager
    - name: infrastructure-gateway-api
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/clusters/infrastructure/base/longhorn
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-authentik
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure-cert-manager
    - name: infrastructure-longhorn
    - name: infrastructure-gateway-api
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/clusters/infrastructure/base/authentik
  prune: true
  wait: true
  timeout: 10m
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-sonarqube
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure-cert-manager
    - name: infrastructure-longhorn
    - name: infrastructure-gateway-api
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/clusters/infrastructure/base/sonarqube
  prune: true
  wait: true
  timeout: 10m
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-github-arc-runner
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/clusters/infrastructure/base/github-arc-runner
  prune: true
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-github-arc-runner-scale
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/clusters/infrastructure/base/github-arc-runner-scale
  prune: true
  wait: true
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-influxdb
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure-longhorn
    - name: infrastructure-gateway-api
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/clusters/infrastructure/base/influxdb
  prune: true
  wait: true
  timeout: 10m
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-flux-notifications
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/clusters/infrastructure/base/flux-notifications
  prune: true
  wait: true
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-prometheus
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure-tailscale-config
    - name: infrastructure-longhorn
    - name: infrastructure-gateway-api
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/clusters/infrastructure/base/prometheus
  prune: true
  wait: true
  timeout: 15m
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg