apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: prometheus-grafana
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:EWQtUfg=,iv:k5buAlHmSvyXQDPwp2iXjyPhNdpHb7/Glbbrk9kJKY0=,tag:ObPTEr8b4HnEvj0qyKVsyw==,type:str]
    admin-password: ENC[AES256_GCM,data:jZn38yY=,iv:olQmgsO8acXrcDRt3+1YKjmnSzIrcFsA9S9gtCWW+Eo=,tag:wMcxJAhuIstU71jK5q35Aw==,type:str]
sops:
    lastmodified: "2026-03-06T20:52:51Z"
    mac: ENC[AES256_GCM,data:q5nlA5XL7DjYh3n6inTGrYUmgAoG44/fQUvZxD3elFbUK4hdUJGVMctxiBb2uBqoKzE5gLezk8WRWmf89TR/PYaB1hJ8dvTII+xF4kZPwKLBXSI1NaLO8gUiIsLggd4IMwTt9DFqCVegv+HI/TSyN/OsEm/kXgN5YLEH6wGhRoE=,iv:BNpGQrLKI40x9XGt2jnu1wuZX0CjSwNbYE4AybGGl/Y=,tag:LeTBuSSseSyYr+sZCuDU0w==,type:str]
    pgp:
        - created_at: "2026-03-06T20:52:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5XGugaz6vRlAQ/8D41OgrTE5qqIWKblZ1CX8ENO5RRCx2OrFWH4Bup0k4Ye
            E9HAJ6nUn8pVq4HEdp+yMtFX5AS/PfY/G8Azah8Xl5YMvrcF6+hvwd2xkvV1FkhB
            o8KU4lz4WoBQydZ4pwrJwREp0lU7LPR0K4SMT6e1FDJD4J5zo7SUCFPE+opuXVdA
            IP++P2VHmXMVl73QxFWVnlF/ZSPhcBboMo9fmVVwEBGzfLwmg2EbNWIUK370Et1z
            /E+7yFFykIwhjDbiYrXglWaLFHMvvs9afv6R0KTlNterq/xNJYbasgVjldi0qs0q
            k4erzC/gxasVGbIzaEOazNCdqYWVUBK9m6rG66fXnuo+0Gup/7ZEEclHcly/3w0u
            SASaS381d22rL+ox3LMnf1vvAVJE0E/oTKj5Q4ksgBb7zU99l27yDzmeVG32o/D3
            frGUtYMj1lvMnK5h7GmR8DXPJG3sHZuZBjO1Z7XOzE7+y67xHAvXBTQHx3bSntDE
            8so/vdQjV3XEMeXOtLh+gXGEZN6ZJidPfSeEuk0F5EjirzVbtSD3Drcc9cjUT88i
            3F/SOfg5rXRgx7NGKYuwe+FXQ1ezlJtX7Jk1KAdToCEECaIORoc8FTssOzTW4Lue
            6rozlbYNsqpBryfrIxrh28sRVVkjP604oJtCmNuqOe+enLsur6MSdHZVqxS1uNbU
            aAEJAhBEaz8G8xSQq5+P8cDj0gEvx//QgEa3GIiIcMASqGnWenEWZjV92BqaMgig
            8HAK9vdHATkDDU1tAXYxocvSOAr4TiNrHDTwP5CIkAKCovXE4wGJYvfIfzmABhTX
            B0i0kFG7vI1o
            =nCLn
            -----END PGP MESSAGE-----
          fp: FB5C16FB8DB546BB01DE0ED9DCCC989D57A72B56
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
