apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: prometheus-grafana
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:7egEnI8=,iv:xODQJb6pmzLvmMZSznA5ZFtQc2yLqP028Te35yb6tLo=,tag:/yEXEk2sAqquMgl2nfSA9A==,type:str]
    admin-password: ENC[AES256_GCM,data:kMGLBCAOROQ=,iv:35iXBto6gb94Y62uFzSq63zQIzh8pex9RoLi/2X4JLY=,tag:lYVeyG4+5nkoW8X3rAoBow==,type:str]
sops:
    lastmodified: "2026-03-06T20:42:37Z"
    mac: ENC[AES256_GCM,data:zEphKzccpc+DELnGwztGSsfuevrd6xfWiwof99Y+9l482lOzVl4D3iwwZ7pYPVYntMfP642qiH3NzLJpOJTLkef0nXo0BjfCUf2iqRZqaq8lOSU5e6SmXLPQn/7oisvAqKfYaPvod+ei02mNCp4lAi8ttdhpSxZUY5wFPa1eNzg=,iv:5T2WkeywZF1gXipPxPU8InpAk8jCTALPrUaTiK82B+k=,tag:eJNryLLADpPq/XqE63WsHA==,type:str]
    pgp:
        - created_at: "2026-03-06T20:34:04Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5XGugaz6vRlAQ/8ClTSe1jiSrQKXAKN7+4iAltjZKXnRV02r3S+6tySDdiL
            bWXvEkuNes7gJlu4VK5kgbx88XUDVnHlrMfUzWmcauNaLlXo1Z3AEMU8aA/4/VKi
            knMkI6d+yZIm5+tX+L4J+OZpwCl6JLb0lsEnPnn+HdGVaxVbr4fZmCsceuSZCU4E
            n2qM2b/O0bgaIqpCx0tuoz9MH9Ptpf3eThDg3eE4F/kf9Ch3x4svsDbv7rsgVt+e
            a7LJpKBZLbtm2VCYXPOU2chWqUsS/AkddhV0wCswWNSEx2WJZHaRYFiiJW2U8PH5
            pqe6vyiSkrREpaT5Z+7GLI/Ha2S4W7pguPpFtPROcInOWqDScxCVj1NvyPetoN+0
            OFiDl2hWur7mDkQOIinR3Gq2otMOMBfk5f6UvrzsuDllTxURJP73KhwEmoDrHLBD
            p50GxKxQI63bemsUz+KbBSh+oMzK+crHyTfuUk8f8lZD4Nfmkm5SYauv7dvuHXtx
            ifyP+N9CAM/9fYgngIBP/dc3Tq5yJP2f41lgmNvoBeGSaP5NLBu+6sqmFXK/HFh6
            dZlwBRl6bJJKB23LFwsRzO8F9+6qFl4PbZ6tKBcb+/SypqR29pydsT7PQb5SzYef
            MpmtewAz4lPnkavDn/LOVYZ51xHnbom9jyP+1PjD2MyQT0UhmYF1UBuSgPNf1szU
            ZgEJAhA5lpeHoPSOc4NIGGg9wV3R6OhcmObvd5LgX71lWbCWw59/O0rH10k6NERG
            HmfRCbpM39QTFSfMDVlfymFVhCD91Wq/Le8XtaQ5Coz8oca0QqTsLVAGlCJjFXDd
            wu2LbnxiYw==
            =9UGt
            -----END PGP MESSAGE-----
          fp: FB5C16FB8DB546BB01DE0ED9DCCC989D57A72B56
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
