apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-tailscale-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/rburtelow/automation-homelab.git
    targetRevision: main
    path: ./flux/clusters/infrastructure/base/tailscale-config
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

