apiVersion: v1
kind: Secret
metadata:
    name: homepage-widget-secrets
    namespace: homepage
type: Opaque
stringData:
    proxmox_api_token_id: ENC[AES256_GCM,data:3YT2yy9P63RJ7S16M5ieiw==,iv:w9J5gxfYiNcu0dzrkYcQWSc/+GASh9j8BCy/xexrHHs=,tag:QAH7jIGb7xQY6LHhPaKP4A==,type:str]
    proxmox_api_token_secret: ENC[AES256_GCM,data:sKwe9JuKXSrLJx+AO5+V9+cv2sPYy3ekyCu4/vZRo3fVx+8h,iv:nqQT3SIub4WCvo7Q6dw0k6QlHtYBcZeC2JNqiMJFksw=,tag:KBPE9R89U58dmuZrH1rLWw==,type:str]
    weather_label: ENC[AES256_GCM,data:rgymbyv5Qd+Cyjs=,iv:zb6fCkAD16Emk57tmUtwx/tcpshBhg2drPSw0NEO9vM=,tag:ABm8sCO5GW6VFYcYntSu1g==,type:str]
    latitude: ENC[AES256_GCM,data:ltA4YoB0dDO+4Q==,iv:rD4M84rmjaFEhI3dd/XnFYEEgEEyaquQKxovczPUGno=,tag:d8hMBR1uhaZ4Og/A7x9lGg==,type:str]
    longitude: ENC[AES256_GCM,data:NRUpcZMO0/Cp2A==,iv:wb4oLWoX6/zeC0qpYXicovY+G4rUczwH9d8Njjp7wHw=,tag:8VNxkMhGHykmMYUI3XQ8Dg==,type:str]
    openweathermap_key: ENC[AES256_GCM,data:Z6f2LFaD5esjNgJ/BVi5SaCgzMLDauwEGC0hoPSCkNU=,iv:OWu1YXHYTym9sAAm1+xJPwAgbF8XMqd2CEvDFHU6Bas=,tag:IighuDS8YqHRIG00qHpl9w==,type:str]
    authentik_url: ENC[AES256_GCM,data:HiqC/xpoEkxojpR7pK93UkVl1I9Jt761lyHB6enHyQz136tw1b5UNQ29Zgi6im11xQGD,iv:tDf2J8nn/1t0COePoW95AJXyB1bReOcQmbAdpAdujRc=,tag:J8EtEaQALNDxtcI70GLGuA==,type:str]
    authentik_api_key: ENC[AES256_GCM,data:FlMqGbNbCmWX/D/8+B8nRvybBKE5GFwWZyo2P0Zwt6cM9BBUT82CcfS+uEVTNMbeh0O0U4FbiM5sbUg6,iv:o9AEHhQN5S7AgWWHcRu9t/HsaUoUmJmX03sN5nro74o=,tag:Mhib+NKoxLFYUUYm2CirXg==,type:str]
    tailscale_key: ENC[AES256_GCM,data:qm0LKMxuhM7fYUQ4GwKykUs2Ad6GRjGXX1zcUfjNeo4e7VxzXIQlhAJcyhWPMykhwOWyWqS/dWCS9/Tahw==,iv:pY6mpWsn43LkbpLWNNDr535jvVKxGNIWj3xdTdatWZw=,tag:Ydv8IMJu8OcKI6s1kPpaRw==,type:str]
    tailscale_deviceid: ENC[AES256_GCM,data:W/y4AE8zzh75iDnvLHddKhI=,iv:yO0IVNlDbdjil79IFmbukvdVsp+3SOM+9JgMzaA29Kc=,tag:VtCNZ1VcG/Dz8pkwB49uRw==,type:str]
    nextcloud_username: ENC[AES256_GCM,data:O1uuYxw=,iv:CNjZnk+TIYGl916hh5g/ZrorRa93/csrUcNaZtSJD3U=,tag:RNs4zCcUGn4uEdIZ6XXjjA==,type:str]
    nextcloud_password: ENC[AES256_GCM,data:WPxpn769V3gdByn0,iv:okf3rc/Q/7TBlsMHqo0WVQBCONFwCIXUBSttJX/3yx0=,tag:EggOIR0EhazdACnNwUKP6Q==,type:str]
sops:
    lastmodified: "2026-03-03T01:38:25Z"
    mac: ENC[AES256_GCM,data:8NRY/cJw4J3JruziCcRJkzkA02K28gpwkfp9+qj2MXswHnagiB7dBlIuI11z1smnoSs5ddMeSL23z+CROH7JNmMpFZape28AGIsb6gbQaMHmk1BXgq63d930MnTaVgTpg1nHzg9QEPTx7drtNWFgb5ao6s1ysRwxB4RKAGQpJJw=,iv:aF11jw+baFfVDYbKIwKKPKSQiR354z74Oc5HNYMkRGI=,tag:Q+aWbrnFfb0JnVrvMP9ifA==,type:str]
    pgp:
        - created_at: "2025-10-07T20:08:42Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5XGugaz6vRlAQ//YJ9ytcPZaqZuziBHPZHidc8xyPMBoYV2U4LIZcPtyqsh
            OrtMkvsITwarFPblevYghrg3Iaf7gQxcZ2scKGT+IfDlyLrBh4MtaIFbahEQnaRW
            BsjSoOh54/uKh0KO779fCqDvax109C07W+nzpphaTsY+jttX4k4AzrQWNPJ3DFHH
            Zl6LYA2sl8KxBUDLxKfKkjzUe+41GbwTI+5iN+RMVJVPIImtr93s+X3hhLTfgY6T
            uiSuwyknOzmUBTpCgq09rmQm2c9P9uJ2MnvkeBaDerOz6z9pgz1yuoZRC+vsYSpn
            v7nWn/AldZEOfvP6eDVHLGSCd6JOB6UijY2QLi2izAmCUQS4Q4Rm7NrJ1amFyrke
            s5R47frtFpfhi6l/dEGfsNY0nsYKC6OjlUZdgW3KjviSamDBJTnGj+6qOD0oQToQ
            yOd+HnTJBkmwGqpJLw4mLeMmpLCd3bb0Og6XrPnFO8E7EA36w8RKw2RbF3uvFaXK
            zOXJU8LCfIgCQdCcYWRwjjKPps8stXRf1CPy4FFQJb6hYhjsQBdT5wH0H+OFo1yV
            hW5rH44lYMv9EjlGCM1510tRYhPAzNRy++8PcaxnyKb9KjJl2HrghcVpyaR6ilmC
            l4oRCOpQoiwZ/2Bb2fW6VezpwlhSyH4Z4/st/5XC+I91XWXxAx/rZORD5MLKSwHU
            aAEJAhDhCHf0x8M3A0cTbjb45QNvcg9U9Dc8ThHhE07to7VPx9upvPLu2OHcCR5r
            Gm4DSBURHjVOlRq4mz+h84uCkpa99baH9VG+S4oifIUZxgntPstTtmYwtWgEKWgU
            mhgjED8FmrQZ
            =pevi
            -----END PGP MESSAGE-----
          fp: FB5C16FB8DB546BB01DE0ED9DCCC989D57A72B56
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
