apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: getajob
  namespace: getajob
spec:
  interval: 10m0s
  timeout: 5m0s
  chart:
    spec:
      chart: getajob
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: getajob
        namespace: getajob
      interval: 10m0s
  values:
    image:
      repository: ghcr.io/rburtelow/getajob
      tag: "latest"
    ingress:
      enabled: true
      className: tailscale
      host: getajob
      tls: true
      tlsSecretName: getajob
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: getajob
            patch: |
              - op: add
                path: /spec/template/spec/imagePullSecrets
                value:
                  - name: ghcr-pull-secret
          - target:
              kind: Ingress
              name: getajob
            patch: |
              - op: add
                path: /metadata/annotations/tailscale.com~1proxy-group
                value: tailscale
