apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: awx-operator
  namespace: awx-operator
spec:
  interval: 10m0s
  url: https://ansible-community.github.io/awx-operator-helm/
