apiVersion: v1
kind: Secret
metadata:
    name: tailscale-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:+eOdkLr18B7QfInuy7YylWw=,iv:i07wMsBZBB/u62p/vTVPbSBGiOJIBFkwO6h/a6fLmYk=,tag:PMrqaXKZZ3+MtEAc40J0Lw==,type:str]
    client_secret: ENC[AES256_GCM,data:i5aFqCOicl0QK5+fLO99xusQz6Sad3QqfFhBMHKSoqmKo9q2sQzO67hWkvcY1PAC6MI7an8be9NbY2Ux0cfw,iv:NuPYmetpehI+Acstw7CYgQ9biVslp1WDDMFK7eXg0xU=,tag:eIUCKF5ujwidhhhhzKlmow==,type:str]
sops:
    lastmodified: "2025-10-05T22:09:44Z"
    mac: ENC[AES256_GCM,data:e24R6GwSypNIDV5OSe0bGhVZRYENHk34pVRSLD5NKooe9Gv5sIQAqeExvUpqYBniIE6Za9SYS8d0Ju16DG3hA9q9dfAfrZi7gBYuF456OfMOozM+KX0tvpzXRKF3JR3nLG7lGM7bzt7PgSK7qdv5Q/uwWmLhYP4IbDXp26fsT78=,iv:mfDJxVtxsWeQ6BlXenJmF8yhuw+T2xprrqoA4Kq4wao=,tag:ekMVjgUnH1igbAcsMEsNKg==,type:str]
    pgp:
        - created_at: "2025-10-05T22:09:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5XGugaz6vRlAQ/+N9EUkI1y5UVPNbinZJLF3lN0TdsucYbrVCfw95eOJP5i
            AuEW5H0kTjlSLyHm6H5hssGbB1TCulJfwuIZYItkuTHzyHGItwXafIqdxWCVNGDl
            W9FXGy9NHYdtRUkMOKL1XDAL+wVeuH1+ae0H7y7/PWhiJAdse9W3ON7HxVvxmifV
            mmLYBdXvcRNWrSObL2uJsizHm989IfhKkkh+Idb5ErM5iddA0p0ajYNxDOHvY3Ks
            RE6C9R6LXq6CcOiyTBzU122xsmDWK/Vv1iHB/yls5oNnw+kZAq6TCunZw/EoXMFa
            gAI6M3EWAH13+WweneAKe6DmHUstA2GQt01/SCr5D/pZyK29CJlPTrXGKlyua0x8
            XfGW815mNb18RMMqzLOlN4J+q+qEbPhbzGMfXdEqL0YXkS2MnZ9x95ZmjaHBy0ZM
            dE6ViK0zFOzUGpcsHQrX9enJzI6ZGssGS4HA4O0fz0E3ES45qAdlex2eUTjXx35/
            EWBOyP9bC7v5G4v2iYjEc5Y+IGIgPXlIayzr/n4LuJxwThk4wOGtYH4GF41TFOb9
            2fjxDNL5OensHpPJibapOJ6mf79JXAFxBydQRqgcHlHJKs+8eEqfDaUpOKbSoMS6
            g5RSlIc9BZD3mcnTOsLocxhcq1zfbka7+VvVFV06dnx9SHeLABNhxE/gX3K2iK7U
            aAEJAhC68p0DE7pO2a5+2SBXIwIkI/xddP0e+b9uqO8DBtJfunmXv1MUIXk+NyV2
            PVy7Iyo6VxOLMmreqgfCQM5n+YTqQf3dETBRXAIuNCpdMLDUQhWMYO250/WIEScx
            bDHLGUNUGnTq
            =4UV9
            -----END PGP MESSAGE-----
          fp: FB5C16FB8DB546BB01DE0ED9DCCC989D57A72B56
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
