apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    secret_key: ENC[AES256_GCM,data:xLo0SsQAzAVKWPR835vrFYZrsBsZ6eDM/SeaOddbS0zALy4vUe5+0UfPXW68H17LeQrxYpzJToh9OheaIXWg1qETm1H0huD/IRi4KyHn1+I=,iv:kCLjTOBwLKiURd6esm1j63vyJ3rsw7YNHqmpWtOjdhE=,tag:Dh2v0XNwgB/HyVKd2yXA+Q==,type:str]
    postgres_password: ENC[AES256_GCM,data:2LaZ8TIQVTMLCeshcNWeig==,iv:iv+79qAmKW1mmxgYt0JtxV8FpF7lj4WeU5OAdL5zUwQ=,tag:4q/QE1F4su72fSj3cu3mOQ==,type:str]
    auth_password: ENC[AES256_GCM,data:wx+zwxE9RrfnOD91pQlSkQ==,iv:hhttZfaEmWyMIx1KNyY8DGzjzkl8MK/zenOgvh2JYFA=,tag:TT75LhM1NFAqsYWYSTPUTg==,type:str]
    hosts: ENC[AES256_GCM,data:+gt9DtYJl1Ag1QORNtGpq9dFZ+OnafyszGV7gzjw,iv:Nqasm+v7pRYO1+GHP47cOO7vIZugdUabbaCX42ns5QA=,tag:CnZCQirEIungMxK7zIGg4Q==,type:str]
sops:
    lastmodified: "2025-10-05T16:30:44Z"
    mac: ENC[AES256_GCM,data:3DADFa5lbC7pxaoM84VjoS8GvRvUZLkdU10BmqmvuI6PwbLSnFO52GxIKskbajFa1gSM676WvPndCGCIFRHW0Fs1fnbpoFC2X1VfO3ac8tQAOaOHWlFLTbzhTn0L+qL82XB/mJ7sppZVmd2zdTLrcEl06DTVqzQcnvYqTIfkcIg=,iv:yYN7jXG/grl/o8h3+X+J+tHcnR+fnvWPwFPS3cJdVco=,tag:kjBN2gdUFVi3xy2ngGYqXg==,type:str]
    pgp:
        - created_at: "2025-10-05T16:30:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5XGugaz6vRlARAAmWYpTw6cCyvA45UJggjKE/NdC+m8CGpX4Dk35heKSMTM
            RPpRH0kJRylUcGehEwFW7LF1JTYvrkut+Hp5Oj3mMfmkxtinSu2vKBruK2MItrlV
            qnAxuoRao6p0frKnIIPeVTZtm4GOZyiYtqTLrypMDZFF5z0Ofv6SxO9KB3RNtc9C
            yrUZZuJmw5sWFlFg27x7bU+I+xtrggKFGk6Nvsr6MkQCswq75v/GcsrXGhm9bEYr
            fs7nyP20FHJR3VgQCvfeX19HxljsSRfuA3ef6gpevCTPz+suhvslOU0ZixMtPP3J
            1h82XVZppGNR1LY5PEBwJqEL1K2nlANU3hrz8vasdBo4IZXVT+czyiyVu/uItHx5
            XRAh/TDhOkN0PFK9acaMxwlqhX41nxBY7JQ80N7jQagWKjKOHKESJDMjvPm+qmoh
            0lN1SG9Pez/R7firldC0wfhNR674bbXL+r3w9W5EWDQJzvHAQrL+bGlznvJv2t98
            IOLybGwkq025qrwM2ohO4FTmB7OvHbl0ehdUmAnnvIr70BiOObdjSUJx58vndPBM
            x/XzQBUxKmytVEnSheiBJ6rbsqk2b0locq9IJX45k/dZs5Vsfh4BO7FK9zRL2lW+
            8t6Ay95VAwq5kXGjp/UsxPfFV5OUGbj+RfVvl/yJavfr2LbJ8WDV8PAOJHCvbh7U
            ZgEJAhBBcDJ4GzEsp8wR2ZCyDMMipPQBXzMyxsfSWnT2eL3rtxq4txTkiaU3HZhg
            KffXeDNSmYpD5MTRS4CmyxhDuT/DnXM1etHt7EdF604qbyJ6x8fPWAfmkKaXsCKQ
            wALWN56Pzw==
            =Vy78
            -----END PGP MESSAGE-----
          fp: FB5C16FB8DB546BB01DE0ED9DCCC989D57A72B56
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
