apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: awx-db
  namespace: awx
spec:
  instances: 1

  storage:
    size: 10Gi

  bootstrap:
    initdb:
      database: awx
      owner: awx
      secret:
        name: awx-db-password
