apiVersion: v1
kind: Secret
metadata:
    name: influxdb-secret
    namespace: influxdb
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:10aDeFUOO10=,iv:ApD8d1mLJakpxWFVXov+n7fnPTcBH5szb7X4Rgw5eJU=,tag:qHAQzlJNOizF+pETTYsjHw==,type:str]
    admin-token: ENC[AES256_GCM,data:xzsz6E+n5RBmJTUjs9zndsTyXdQVUfePzQy853Owk8pFETJ1gktSkZ6EC02lthZSJqGvE6vUVNLYWoJLYTaetA==,iv:vlfBSCLWe/z6JQiAJOGFZPD3TOjNpV2ElXmhmrhzk3U=,tag:EOYYelgAqrxIWOszqZ7mXQ==,type:str]
sops:
    lastmodified: "2026-03-02T03:22:36Z"
    mac: ENC[AES256_GCM,data:182ZXRax7EBt7EsOB0Pp7rwI9QkmGn/bVKP2GhrrT9/Srj0Pr+5sFCGwrhP5EXLYvkt0UtPh7FriTHXyymWqVvlnAYZVrRW0BeREMUBDWITAwlKul9XED2oB0AX8qt7nRHUt8z35XvwPWJb7RmmeYT+xmH0oBDzFy8nGRTF9x5Y=,iv:imFXZd1HjLmHXcqMxnoXzQ2jsllnqeLlXRMG7DqXwZQ=,tag:OkoV0Hi2duwR2MBxLNZqvg==,type:str]
    pgp:
        - created_at: "2026-03-02T03:21:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5XGugaz6vRlAQ//UykfKBWMUQKDqwYVQE1GVon5yTRhosaGSd8zE1cqDr08
            zOEKbeh3rxnbO7p7uw6BUUJBImxfOJuCJLFmUdwDYNAaRpU9yr7FpKOcKHhpcF8W
            bTkr+YdO7Fo6CXnXAa6BRhppHTMBzEgQkrvDmdiR0gt+Yvsgo4chhRhe4pT4er/f
            8n6VrQxmtCZ3rA1QKL7uX4/rNzGxSEPRIG4Pam96ZmsD2DvIKVglcNp2IT2G2pmb
            FZXH1oggC4aS6nlPwbQ8W20oA5gaQdUHeoFmAWtzyHLmxNfGwB3ofMwDGjKm/LuG
            jUzbRxi5SBsYKQRutZHO4luDBdygmvqfehbxFTI/1X36EiWWkaT0EWkplKtqKsWL
            sceZgVeEGTIS029c+cOl7Yvxi+BiGuu5Mi6aZwLMxc+qJQTbQz9lu+hntsyiflYn
            KEpcq0igRTmqheEy4HPy6OmH2zFyYoPmM2s3oDZ/xuA2J5MvBZ691zgitePtZaCx
            2+vRRmP4+1WKqIjvc8pXosr0h8TAmd8rVh5WoNr6+ynfYLAzpkCwvmjLXjPeR2nV
            RJZQ59TWiMpzDyBz7rAzA8yUaSdF1EuV3j4punsTTmmwBbFsCYsobFqImvmoFu86
            UFhG2eHbty4Kpzgk/WMnX8meRsvWiMl2Sui36Of6xZ0jo/xx1Z3Emba0vFq2b1HU
            aAEJAhCYhYb1EPe/jC7hbR7tV/E8vvol/TfUIry8qT+tCW2hMRkLdsTZOGz6qFds
            qEDxS1bYZ1Beg1/kUfj7y8bAtZzh9pfx8Czio1wM92fXeCzQ57+dGBJFHaJUgGvZ
            AnnzKlKz4bqa
            =rC+J
            -----END PGP MESSAGE-----
          fp: FB5C16FB8DB546BB01DE0ED9DCCC989D57A72B56
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
