apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infrastructure/cert-manager.yaml
  - infrastructure/longhorn.yaml
  - infrastructure/metrics-server.yaml
  - infrastructure/strimzi.yaml
  - infrastructure/tailscale.yaml
  - infrastructure/tailscale-config.yaml
  - infrastructure/authentik.yaml
  - infrastructure/sonarqube.yaml
  - infrastructure/prometheus-grafana.yaml
  - apps/homepage.yaml
  - apps/mongodb-running-race-tracker.yaml
  - apps/redis-running-race-tracker.yaml
  - apps/strimzi-running-race-tracker.yaml
  - apps/kafka-topics-running-race-tracker.yaml
  - apps/live-tracking-running-race-tracker.yaml
  - apps/race-management-running-race-tracker.yaml
  - apps/runner-registration-running-race-tracker.yaml
  - apps/simulation-running-race-tracker.yaml

