apiVersion: v1
kind: Secret
metadata:
    name: kestra-env
    namespace: kestra
type: Opaque
stringData:
    #ENC[AES256_GCM,data:vpMFQem9luEwUKTCT0rkrb0WDkLoU+Y7k016qvPP0N+Sd4kX,iv:iz0QndXAIB2Pr/kyoTHiErWgpoctrg0vfXw8UZhAFSM=,tag:lAmpV6Bn5qrKl5t9TGs2qg==,type:comment]
    #ENC[AES256_GCM,data:2M3rtnkeWCNMvI1u0HAKbdOQ7Q==,iv:GAYKcDpUuz218YxrK6xGXS4BzJ4Q31LG2bKESUEVHzc=,tag:JqMtzHTwS4jlrhG34upiAA==,type:comment]
    #ENC[AES256_GCM,data:ljV6f8Frte+/DcYX6ZxV1ifXdjrtgdCSgdbY9hv6qyaLe7Z2c3IqlMRfIzbJrqKehL+siCqEgw==,iv:hgyBBMzj8jZufghHhch94rhDEtk9l2q5OnDfpt+l9Sg=,tag:2cR3nvEwZntD/cQGjD6kZw==,type:comment]
    #ENC[AES256_GCM,data:cA3BrpboKRnoRGd0c707t3kp24hCwB0SsOSME4A=,iv:jTvX+a07MA5rwc9LuI+lzp2r42dcBhvYelvclVyLfAw=,tag:kIAvU2+TL1eQuI1X5X06pA==,type:comment]
    #ENC[AES256_GCM,data:mQXWfJimbemHHz7S7jCR7CR/Kr8dMB0AvEce,iv:lPqeT/N/RqiODfd8ORmNjn52kWH/7G9bhHw2YGGXBr4=,tag:R+tbHm79wJh+4hQV0Q6DXQ==,type:comment]
    SECRET_GITHUB_PAT: ENC[AES256_GCM,data:+6AJ5gziQn15VYpA0mYI4N+cYeB2qGmYROW5RFWbOf7YhayH321pow==,iv:7fzUOTBLt1bTUFBX5m/x7o+7ux3Vhx4FPydfdxWVqOU=,tag:9YmmLLe2TPzNmcMee5EePA==,type:str]
    SECRET_GITHUB_USERNAME: ENC[AES256_GCM,data:llCflVuXk5Kt,iv:Jeo6w2jTLeeTOD9swC5VvlUC511uDtqsfgx5lDC7qlg=,tag:iRUx8BF4u5x37jAnBYaKhA==,type:str]
sops:
    lastmodified: "2026-03-04T17:00:59Z"
    mac: ENC[AES256_GCM,data:BIBUfssSfzchKhw0F397wM56VlUHkWzw3qVKHb7HgK7WAebWg/fUHMRbgiLxK+GDC6KXtG9SqnYt/hWcqRfHyv+hKwRa0vJEdynG1jsQdoA0sIphBax1FaH3pap4OQkLEHTbIGi6VfzuwLi66Nw3Xl9nkqQCYE2NDKNi/Quc5hE=,iv:hsCpWyoKjGyioDc8SQHC1Bb2BUJV1d3sG/M2z34LRQ4=,tag:letgmPwh519YhMlVYbsJ5Q==,type:str]
    pgp:
        - created_at: "2026-03-04T02:16:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA5XGugaz6vRlAQ//cJzAa5ju5BkviKmE54RaS1Exf9uF31K7/bEgtwOJ6/F0
            ciuxVV34KSOX3YAyAZnAQdkvsdJPl+gDPYxTPLIgBfLi5MMEDQr/kJFUS2IZVZrU
            mbUvHTmyKQ1TyGyprj//8EBpZNYdg2s6VJefLtlqorYoC/UT4N96vM72lLmhq+Ev
            zBKjMCoewsTqA3lvHhspsqUnPekPbHz8pvg4dayqiXYbUuaK+cXyv9o65lSKMXJY
            mPiUNgonWLYAnQYszZA6eBp688l3ziN7vA4ZNj3dZZ2O9KQAg8G640raCM/AIScN
            ZfKZxkxL9X1rPTHt3VMnuIk6EEbOVkyjB2nUphlaDZ4MHzZQwwkxT+oqtJHWpKMU
            MY+KMNrZa4LuNofxInvtYeKdn5JmEi6kpMZ0GmpubUFyoRwGsp5vaaAKwj+m3gft
            U/lP6OMrffIFKAG9Oe43jII9VR2vvcOGELaSnhw0lxqpHlH0VvfOO0PqmobWb1l+
            kiwh9jPMDovfdMMkTRjGtF3qVS3VnRTvfOnSuoy+YEGvR8Mfa0AR+x/R5kP2x8sy
            oKqsyFEWWKojQM9a/n1uwBpoQ6iu3lPGcvVy/pgKGB11n7e3vQqpivS+gab90CAV
            n7kPm1bg55SwS2Y4IzhaP1PrxItfTBvxt7sUnLbwWHOhsxAdpwRUR9UbtefZueXU
            aAEJAhAyKm2zJL9asC6ljdxzx7r18kd7UcFx7K0IYpt09m9KhQoJoFeXDNynaFO4
            7NhKk85lH5bKEE+R6cWvHtw9RpHPHC7O4w9QqDfcY+dIoYHmXeFtVSBW8Fl0syfl
            ULGGvXB5nIOK
            =Hz3A
            -----END PGP MESSAGE-----
          fp: FB5C16FB8DB546BB01DE0ED9DCCC989D57A72B56
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
